header_links:
  About: "#about"

rss: /atom.xml

profile_picture: /images/profile.png

since: 2015

widgets:
- recents
- categories
- tags
- archives

social_links:
  twitter: https://twitter.com/BaoDangDev
  github: https://github.com/baodang
  envelope: "mailto:dangvinhbao@gmail.com"
  rss: /atom.xml
