header_links:
  About: "#about"

rss: /atom.xml

profile_picture: /images/profile.png

highlight_theme: tomorrow-night-eighties

since: 2015

widgets:
- archives
- recents
- categories
- tags

social_links:
  twitter: https://twitter.com/BaoDelta
  github: https://github.com/BaoDelta
  envelope: "mailto:dangvinhbao@gmail.com"
  rss: /atom.xml

# google_analytics:
