header_links:
  Archives: /archives
  Page: /page
  About: "#about"

rss: /atom.xml

# profile_picture: /images/profile.png

since: 2015

widgets:
- archives
- recents
- categories
- tags
- tagcloud

# social_links:
#   twitter: twitter_url
#   github: github_url
#   envelope: mailto_url
#   rss: rss_url
