header_links:
  About: "#about"

rss: /atom.xml

# profile_picture: /images/profile.png

since: 2015

widgets:
- recents
- categories
- tags
- archives

# social_links:
#   twitter: twitter_url
#   github: github_url
#   envelope: mailto_url
#   rss: rss_url
